schema: "1"
source: " "
metadata:
  name: " "
  owner: "yasnov.artur@gmail.com"

variables:
  - name: namespacePrefix
    defaultValue: "123"

  - name: deployToDev
    defaultValue: false
    
  - name: deployToPre
    defaultValue: false

  - name: kubernetesObjectsName
    defaultValue: ".."

  - name: includeManualJudgment
    defaultValue: true

  - name: targetClusterName
    defaultValue: "prod"

  - name: slackChannel
    defaultValue: "#.."
